
FROM debian:bookworm


RUN apt update && \
    apt install -y mariadb-server && \
    apt clean


COPY conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf


COPY tools/init.sh /usr/local/bin/init.sh


RUN chmod +x /usr/local/bin/init.sh


EXPOSE 3306


ENTRYPOINT ["/usr/local/bin/init.sh"]
